directory = new Object()
directory['ace'] = new Object()
directory['af'] = new Object()
directory['af']['1-welcome.html'] = true
directory['am'] = new Object()
directory['am']['1-welcome.html'] = true
directory['ar'] = new Object()
directory['ar']['1-welcome.html'] = true
directory['ast'] = new Object()
directory['ast']['1-welcome.html'] = true
directory['be'] = new Object()
directory['be']['1-welcome.html'] = true
directory['bg'] = new Object()
directory['bg']['1-welcome.html'] = true
directory['bn'] = new Object()
directory['br'] = new Object()
directory['bs'] = new Object()
directory['bs']['1-welcome.html'] = true
directory['ca'] = new Object()
directory['ca']['1-welcome.html'] = true
directory['ca@valencia'] = new Object()
directory['ca@valencia']['1-welcome.html'] = true
directory['cs'] = new Object()
directory['cs']['1-welcome.html'] = true
directory['csb'] = new Object()
directory['csb']['1-welcome.html'] = true
directory['cy'] = new Object()
directory['cy']['1-welcome.html'] = true
directory['da'] = new Object()
directory['da']['1-welcome.html'] = true
directory['de'] = new Object()
directory['de']['1-welcome.html'] = true
directory['dv'] = new Object()
directory['el'] = new Object()
directory['el']['1-welcome.html'] = true
directory['en_AU'] = new Object()
directory['en_AU']['1-welcome.html'] = true
directory['en_CA'] = new Object()
directory['en_CA']['1-welcome.html'] = true
directory['en_GB'] = new Object()
directory['en_GB']['1-welcome.html'] = true
directory['eo'] = new Object()
directory['eo']['1-welcome.html'] = true
directory['es'] = new Object()
directory['es']['1-welcome.html'] = true
directory['et'] = new Object()
directory['et']['1-welcome.html'] = true
directory['eu'] = new Object()
directory['fa'] = new Object()
directory['fi'] = new Object()
directory['fi']['1-welcome.html'] = true
directory['fr'] = new Object()
directory['fr']['1-welcome.html'] = true
directory['fy'] = new Object()
directory['gd'] = new Object()
directory['gl'] = new Object()
directory['gl']['1-welcome.html'] = true
directory['gu'] = new Object()
directory['gv'] = new Object()
directory['he'] = new Object()
directory['he']['1-welcome.html'] = true
directory['hi'] = new Object()
directory['hi']['1-welcome.html'] = true
directory['hr'] = new Object()
directory['hr']['1-welcome.html'] = true
directory['hu'] = new Object()
directory['hu']['1-welcome.html'] = true
directory['hy'] = new Object()
directory['id'] = new Object()
directory['id']['1-welcome.html'] = true
directory['is'] = new Object()
directory['is']['1-welcome.html'] = true
directory['it'] = new Object()
directory['it']['1-welcome.html'] = true
directory['ja'] = new Object()
directory['ja']['1-welcome.html'] = true
directory['kl'] = new Object()
directory['km'] = new Object()
directory['km']['1-welcome.html'] = true
directory['kn'] = new Object()
directory['ko'] = new Object()
directory['ko']['1-welcome.html'] = true
directory['ku'] = new Object()
directory['ku']['1-welcome.html'] = true
directory['lt'] = new Object()
directory['lv'] = new Object()
directory['ml'] = new Object()
directory['mr'] = new Object()
directory['mr']['1-welcome.html'] = true
directory['ms'] = new Object()
directory['ms']['1-welcome.html'] = true
directory['nb'] = new Object()
directory['nb']['1-welcome.html'] = true
directory['ne'] = new Object()
directory['nl'] = new Object()
directory['nl']['1-welcome.html'] = true
directory['nn'] = new Object()
directory['nn']['1-welcome.html'] = true
directory['ny'] = new Object()
directory['oc'] = new Object()
directory['oc']['1-welcome.html'] = true
directory['pa'] = new Object()
directory['pl'] = new Object()
directory['pl']['1-welcome.html'] = true
directory['ps'] = new Object()
directory['pt'] = new Object()
directory['pt']['1-welcome.html'] = true
directory['pt_BR'] = new Object()
directory['pt_BR']['1-welcome.html'] = true
directory['ro'] = new Object()
directory['ro']['1-welcome.html'] = true
directory['ru'] = new Object()
directory['ru']['1-welcome.html'] = true
directory['sd'] = new Object()
directory['sd']['1-welcome.html'] = true
directory['si'] = new Object()
directory['sk'] = new Object()
directory['sk']['1-welcome.html'] = true
directory['sl'] = new Object()
directory['sl']['1-welcome.html'] = true
directory['sn'] = new Object()
directory['sq'] = new Object()
directory['sq']['1-welcome.html'] = true
directory['sr'] = new Object()
directory['sr']['1-welcome.html'] = true
directory['sv'] = new Object()
directory['sv']['1-welcome.html'] = true
directory['ta'] = new Object()
directory['ta']['1-welcome.html'] = true
directory['th'] = new Object()
directory['th']['1-welcome.html'] = true
directory['tl'] = new Object()
directory['tr'] = new Object()
directory['tr']['1-welcome.html'] = true
directory['ug'] = new Object()
directory['ug']['1-welcome.html'] = true
directory['uk'] = new Object()
directory['uk']['1-welcome.html'] = true
directory['ur'] = new Object()
directory['vi'] = new Object()
directory['vi']['1-welcome.html'] = true
directory['zh_CN'] = new Object()
directory['zh_CN']['1-welcome.html'] = true
directory['zh_HK'] = new Object()
directory['zh_HK']['1-welcome.html'] = true
directory['zh_TW'] = new Object()
directory['zh_TW']['1-welcome.html'] = true
